services:
  db:
    image: postgres:18.1-alpine
    command: >
      postgres 
      -c max_connections=200
      -c shared_buffers=256MB      
      -c effective_cache_size=512MB 
      -c work_mem=3MB              
      -c maintenance_work_mem=64MB
      -c synchronous_commit=off    
      -c fsync=off              
      -c full_page_writes=off   
      -c checkpoint_timeout=10min  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env
    networks:
      - backend-net
    restart: always
    # --- 新增健康檢查 ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'  # 限制 PG 最多用 1 核，留 1 核給 Python
          memory: 1.5G

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - backend-net
    restart: always
    volumes:
      - redis_data:/data
    # --- 修改 command ---
    command: >
      redis-server 
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru 
      --appendonly no 
      --save ""  
      --tcp-backlog 2048 
      --maxclients 1000
    
    sysctls:
      - net.core.somaxconn=2048 # 配合 tcp-backlog 提高系統層面的連線佇列
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    env_file: ./.env
    
    volumes:
      - .:/app
      - static_volume:/app/static
    #  - /home/ubuntu/download/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17:/var/www/static/downloads
    networks:
      - frontend-net
      - backend-net
    # --- 修改 depends_on ---
    depends_on:
      db:
        condition: service_healthy # 等待 db 服務健康
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --loop uvloop --http httptools --no-access-log
    sysctls:
      - net.core.somaxconn=4096
    
  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_main.conf:/etc/nginx/nginx.conf:ro   # 新增這個！覆蓋主設定
      - static_volume:/var/www/static
    #  - /home/ubuntu/download/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17:/var/www/static/downloads
    # 只將 Nginx 服務連接到前端網絡
    networks:
      - frontend-net
    depends_on:
      - backend
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

# 在頂層定義我們自定義的網絡
networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
  